FROM golang:alpine AS build

RUN mkdir /prerankBuild
COPY prerank-stages  /prerankBuild/prerank-stages

WORKDIR /prerankBuild/prerank-stages
RUN go mod download


RUN cd /prerankBuild/prerank-stages/prerank/ && \
    go build -o prerank_cmd  -ldflags="-s -w " main.go 

FROM alpine:latest
COPY --from=build /prerankBuild/prerank-stages/prerank/prerank_cmd /usr/bin/prerank_cmd
COPY prerank-stages/config/  /usr/config/ 
ENTRYPOINT ["/usr/bin/prerank_cmd"]