name: Update RecommendDebug

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Release Tags'

jobs:
  update_rank_amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: beclab/recommenddebug:${{ github.event.inputs.tags }}-amd64
          file: Dockerfile.recommenddebug.amd64
          platforms: linux/amd64

  update_rank_arm64:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      
      - name: Build and push Docker image 
        uses: docker/build-push-action@v3
        with:
            push: true
            tags: beclab/recommenddebug:${{ github.event.inputs.tags }}-arm64
            file: Dockerfile.recommenddebug.arm64
            platforms: linux/arm64

  publish_manifest:
    needs:
      - update_rank_amd64
      - update_rank_arm64
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Push manifest
        run: |
          docker manifest create beclab/recommenddebug:${{ github.event.inputs.tags }} --amend beclab/recommenddebug:${{ github.event.inputs.tags }}-amd64 --amend beclab/recommenddebug:${{ github.event.inputs.tags }}-arm64
          docker manifest push beclab/recommenddebug:${{ github.event.inputs.tags }}
