name: Update Train

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Release Tags'
      target-platform:
        description: 'Target Platform'
        required: true
        default: 'amd64'

jobs:
  update_train:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push Docker image for amd64
        if: ${{ github.event.inputs['target-platform'] == 'amd64' }}
        uses: docker/build-push-action@v3
        with:
            push: true
            tags: beclab/r4train:${{ github.event.inputs.tags }}
            file: Dockerfile.r4train.amd64
            platforms: linux/amd64

      - name: Build and push Docker image for arm64
        if: ${{ github.event.inputs['target-platform'] == 'arm64' }}
        uses: docker/build-push-action@v3
        with:
            push: true
            tags: beclab/r4train:${{ github.event.inputs.tags }}
            file: Dockerfile.r4train.arm64
            platforms: linux/arm64
