name: Update Userembedding

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Release Tags'

jobs:
  update_userembedding:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      
      - name: Build and push Docker image 
        uses: docker/build-push-action@v3
        with:
            push: true
            tags: beclab/r4userembedding:${{ github.event.inputs.tags }}
            file: Dockerfile.r4userembedding
            platforms: linux/amd64,linux/arm64